-- 코드를 입력하세요
SELECT U.USER_ID, U.NICKNAME, CONCAT(U.CITY,' ', U.STREET_ADDRESS1, ' ', U.STREET_ADDRESS2) AS 전체주소, CONCAT(SUBSTR(U.TLNO, 1, 3),'-',SUBSTR(U.TLNO, 4, 4),'-', SUBSTR(U.TLNO, 8)) AS 전화번호
FROM USED_GOODS_USER AS U
JOIN USED_GOODS_BOARD AS B
ON U.USER_ID = B.WRITER_ID
WHERE USER_ID IN (SELECT WRITER_ID
                 FROM USED_GOODS_BOARD
                 GROUP BY WRITER_ID
                 HAVING COUNT(WRITER_ID) >= 3)
group by user_id
ORDER BY USER_ID DESC