-- 코드를 입력하세요
SELECT CAR_TYPE, SUM(CAR_ID IN (SELECT CAR_ID
                               FROM CAR_RENTAL_COMPANY_CAR
                               WHERE OPTIONS LIKE '%열선시트%' OR OPTIONS LIKE '%가죽시트%' OR OPTIONS LIKE '%통풍시트%')) AS CARS
FROM CAR_RENTAL_COMPANY_CAR
GROUP BY CAR_TYPE
ORDER BY CAR_TYPE ASC