-- 코드를 입력하세요
SELECT DISTINCT(H.CAR_ID)
FROM CAR_RENTAL_COMPANY_CAR AS C
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS H
WHERE H.CAR_ID IN (SELECT CAR_ID
                  FROM CAR_RENTAL_COMPANY_CAR
                  WHERE CAR_TYPE = '세단') 
AND H.START_DATE LIKE '2022-10-%'
ORDER BY CAR_ID DESC